# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-gmail}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["BehindLogic"]
  s.date = %q{2010-05-14}
  s.description = %q{A Rubyesque interface to Gmail, with all the tools you'll need. Search, read and send multipart emails; archive, mark as read/unread, delete emails; and manage labels.}
  s.email = %q{gems@behindlogic.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     "History.txt",
     "Manifest.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/gmail.rb",
     "lib/gmail/mailbox.rb",
     "lib/gmail/message.rb",
     "lib/smtp_tls.rb",
     "ruby-gmail.gemspec",
     "test/test_gmail.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://dcparker.github.com/ruby-gmail}
  s.post_install_message = %q{
[34mIf ruby-gmail saves you TWO hours of work, want to compensate me for, like, a half-hour?
Support me in making new and better gems:[0m [31;4mhttp://pledgie.com/campaigns/7087[0m

}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Rubyesque interface to Gmail, with all the tools you'll need.}
  s.test_files = [
    "test/test_gmail.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<shared-mime-info>, [">= 0"])
      s.add_runtime_dependency(%q<mail>, [">= 2.2.1"])
    else
      s.add_dependency(%q<shared-mime-info>, [">= 0"])
      s.add_dependency(%q<mail>, [">= 2.2.1"])
    end
  else
    s.add_dependency(%q<shared-mime-info>, [">= 0"])
    s.add_dependency(%q<mail>, [">= 2.2.1"])
  end
end

